spawnpoints:
  red:
    world: world
    x: 0.0
    y: 64.0
    z: -80.0
    pitch: 10.0
    yaw: 2.0
  
  blue:
    world: world
    x: 81.0
    y: 64.0
    z: 0.0
    pitch: 8.0
    yaw: 91.0
  
  green:
    world: world
    x: 0.0
    y: 64.0
    z: 81.0
    pitch: 6.0
    yaw: -179.0
  
  yellow:
    world: world
    x: -80.0
    y: 64.0
    z: 0.0
    pitch: 14.0
    yaw: -90.0

npcs:
  shop:
  - world: world
    x: 8.0
    y: 62.0
    z: -83.0
    pitch: 0.0
    yaw: 0.0
  - world: world
    x: 83.0
    y: 62.0
    z: 8.0
    pitch: 0.0
    yaw: 0.0
  - world: world
    x: -8.0
    y: 62.0
    z: 83.0
    pitch: 0.0
    yaw: 0.0
  - world: world
    x: -83.0
    y: 62.0
    z: -8.0
    pitch: 0.0
    yaw: 0.0
  
  upgrade:
  - world: world
    x: -8.0
    y: 63.0
    z: -83.0
    pitch: 0.0
    yaw: 0.0
  - world: world
    x: 83.0
    y: 62.0
    z: -8.0
    pitch: 0.0
    yaw: 0.0
  - world: world
    x: 8.0
    y: 62.0
    z: 83.0
    pitch: 0.0
    yaw: 0.0
  - world: world
    x: -83.0
    y: 62.0
    z: 8.0
    pitch: 0.0
    yaw: 0.0

spawners:
- world: world
  x: 0.0
  y: 63.0
  z: -85.0
  pitch: 75.0
  yaw: -1.0
- world: world
  x: 86.0
  y: 63.0
  z: 0.0
  pitch: 77.0
  yaw: 91.0
- world: world
  x: 0.0
  y: 63.0
  z: 86.0
  pitch: 80.0
  yaw: -178.0
- world: world
  x: -85.0
  y: 63.5
  z: 0.0
  pitch: 89.0
  yaw: -94.0

join:
  world: world
  x: 0.0
  y: 139.0
  z: 0.0
  pitch: 4.0
  yaw: -87.0
