name: BedWars
version: 1.2.1
main: cn.nekopixel.bedwars.Main
api-version: 1.20
authors: [BLxcwg666]

depend: [NametagEdit,packetevents]
softdepend: [LuckPerms]

commands:
  bw:
    description: Manage BedWars Plugin
    usage: /bw
    permission: bedwars.admin
    aliases: [bedwars]
  shout:
    description: Shout to all players
    usage: /shout <msg>
    aliases: [s]

permissions:
  bedwars.admin:
    description: Use BedWars Admin Command
    default: op
    children:
      bedwars.status: true
  bedwars.status:
    description: Switch GameStatus
    default: op
