name: BedWars
version: 1.0.0
main: cn.nekopixel.bedwars.Main
api-version: 1.20

commands:
  bw:
    description: 管理 Bedwars 插件
    usage: /bw
    permission: bw.admin

permissions:
  bw.admin:
    description: 使用 Bedwars 管理命令
    default: op
