name: BedWars
version: 1.0.2
main: cn.nekopixel.bedwars.Main
api-version: 1.20
authors: [BLxcwg666]

depend: [NametagEdit,packetevents]
softdepend: [LuckPerms]

commands:
  bw:
    description: 管理 Bedwars 插件
    usage: /bw
    permission: bedwars.admin
    aliases: [bedwars]
  shout:
    description: 向所有玩家喊话
    usage: /shout <msg>
    aliases: [s]

permissions:
  bedwars.admin:
    description: 使用 Bedwars 管理命令
    default: op
    children:
      bedwars.status: true
  bedwars.status:
    description: 允许切换游戏状态
    default: op
