name: Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install 7z
      run: |
        sudo apt-get update
        sudo apt-get install -y p7zip-full

    - name: Download test server
      run: |
        wget -O mc-testserver.7z --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" https://r3.lhf277.top/mc-testserver.7z

    - name: Create server directory and extract
      run: |
        7z x mc-testserver.7z
        cd mc-testserver

    - name: Build project
      run: mvn clean package -DskipTests

    - name: Copy plugin
      run: |
        cp target/BedWars*.jar mc-testserver/plugins/

    - name: Start Minecraft Server
      run: |
        cd mc-testserver
        if ls *.jar 1> /dev/null 2>&1; then
          JAR_FILE=$(ls *.jar | head -1)
          java -Xmx1024M -Xms1024M -jar "$JAR_FILE" nogui > server.log 2>&1 &
        else
          echo "Minecraft Server Jar not found"
          exit 1
        fi
        SERVER_PID=$!
        echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV

    - name: Wait for server startup
      run: |
        sleep 120

    - name: Check server logs
      run: |
        cd mc-testserver
        if grep -i "Error\|ERROR\|Exception\|Severe" logs\latest.log; then
          echo "Found Errors, Failed"
          kill $SERVER_PID 2>/dev/null || true
          exit 1
        else
          echo "Pass"
        fi

    - name: Stop server
      run: |
        kill $SERVER_PID 2>/dev/null || true
        sleep 5
        kill -9 $SERVER_PID 2>/dev/null || true

    - name: Display server logs
      if: always()
      run: |
        cat mc-testserver/logs/latest.log
