name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Environment
      uses: actions/setup-maven@v2
      with:
        java-version: 17
        maven-version: 3.x

    - name: Build
      run: mvn clean package
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./target/*.jar # 注意替换为你实际生成的文件名

